# fly.toml file generated for full-service on 2021-10-07T19:05:14-04:00

app = "full-service"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  RUST_LOG = "info"
  mc_connection = "info"
  mc_ledger_sync = "info"

[mounts]
  destination = "/data"
  source = "ledger"

[experimental]
  allowed_public_ports = []

[[services]]
  http_checks = []
  internal_port = 9090
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
