from setuptools import setup, find_packages

setup(
    name="forestbot",
    packages=find_packages(),
    url="https://github.abc.com/mobilecoinofficial/forestbot",
    description="a forest of signal bots",
    long_description=open("README.md").read(),
    install_requires=[
        "aiodns==3.0.0",
        "aiohttp==3.8.1",
        "aioprocessing==2.0.0",
        "aiosignal==1.2.0",
        "async-timeout==4.0.2",
        "asyncpg==0.25.0",
        "attrs==21.4.0",
        "base58==2.1.1",
        "brotli==1.0.9",
        "cchardet==2.1.7",
        "cffi==1.15.0",
        "charset-normalizer==2.0.11",
        "frozenlist==1.3.0",
        "idna==3.3",
        "multidict==6.0.2",
        "phonenumberslite==8.12.42",
        "prometheus-async==19.2.0",
        "prometheus-client==0.13.1",
        "protobuf==3.19.4",
        "pycares==4.1.2",
        "pycparser==2.21",
        "pycryptodome==3.14.1",
        "termcolor==1.1.0",
        "ulid2==0.3.0",
        "wrapt==1.13.3",
        "yarl==1.7.2",
    ],
    # dependency_links = [
    #  "git+git://github.abc.com/abc/SomePrivateLib.git#egg=SomePrivateLib",
    # ],
    include_package_data=True,
)
