apiVersion: batch/v1
kind: Job
metadata:
  name: imagegen-job-free
  namespace: tenant-mobilecoin-imogen
  labels:
      tier: free
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: imogegen
        image: technillogue/imagegen:1.2.11
        # command: ["/usr/bin/sleep"]
        # args: ["1h"]
        resources:
          limits:
            cpu: 3
            memory: 6Gi #idk if it needs this much
            nvidia.com/gpu: 1
        env:
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: dev-secrets
                key: REDIS_URL
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: dev-secrets
                key: DATABASE_URL
          - name: SUPABASE_API_KEY
            valueFrom:
              secretKeyRef:
                name: dev-secrets
                key: SUPABASE_API_KEY
          - name: TWITTER_CREDS
            valueFrom:
              secretKeyRef:
                name: dev-secrets
                key: TWITTER_CREDS
          - name: EXIT # exit when fetching prompt fails on queue empty
            value: "true"
          - name: FREE # parse nonpaid prompts
            value: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - Tesla_V100_PCIE
                  - Tesla_V100_NVLINK
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 20
              preference:
                matchExpressions:
                  - key: gpu.nvidia.com/class
                    operator: In
                    values:
                      - Tesla_V100_PCIE
