---
signal-cli:
  request_obj:
    method: str
    params:
      envelope:
        sourceNumber: str
        sourceUuid: str
        timestamp: str
        dataMessage:
          message: str
          expiresInSeconds: int
          mentions:
          - str
          attachments:
          - contentType: str
          - filename: str
          - id: str
          - size: int
          groupInfo:
            groupId: str
            type: str
        typingMessage:
          action: str
        receiptMessage:
          when: int
          isDelivery: bool
          isRead: bool
          timestamps:
          - int
      error:
        message: str
        type: str
  error_obj:
    code: int
    message: str
  result_obj:
    timestamp: int
signal-cli-metadata:
  message: message
  groupId: group
  attachments: attachments
  dataMessage: data_message
  typingMessage: typing_notification
  receiptMessage: receipt_notification
  error: error
